/**
 * Native Tool Interface
 *
 * Defines the contract for native (built-in) tools.
 */

export interface NativeToolResult {
  success: boolean;
  output?: unknown;
  error?: string;
  /** Files generated by the tool (images, data files, etc.) */
  files?: Array<{
    name: string;
    /** Full data URL with MIME type (e.g., data:image/png;base64,...) */
    dataUrl: string;
    size: number;
    mediaType?: string;
  }>;
}

export interface NativeTool {
  readonly name: string;
  readonly description: string;
  readonly inputSchema: Record<string, unknown>;
  /**
   * When true, this tool is only available to supervisor agents.
   * Private tools are automatically included in supervisor's tool list
   * without explicit configuration, and excluded from other agents
   * unless explicitly granted.
   */
  readonly private?: boolean;

  execute(params: Record<string, unknown>): Promise<NativeToolResult>;
}
